### ISSUE TITLE
frida_without_jailbreak_ipa.png mentioned in the README.md

### ISSUE THREAD

**Issue by ddouhine** [noobpk/frida-ios-hook#1]
I guess the file was just there in the folder but it's not used by the tool.

![Screenshot 2020-09-17 at 09 21 44](https://user-images.githubusercontent.com/4519330/93433675-667efc80-f8c7-11ea-9d8a-6f789ef4a8c6.png)

**Comment by noobpk** [comment]
ohh sorry!! My mistake. I will update readme soon. Thanks bro
