### ISSUE TITLE
failed to get the task for process

### ISSUE THREAD

**Issue by xL0b0** [noobpk/frida-ios-hook#113]
When I'm trying to dump an app, I am getting following log:

[13-02-24 13:30:54] [INFO] - [*] Iproxy process for port 2222 is alive.
[13-02-24 13:30:54] [INFO] - [*] Dumping...
[13-02-24 13:30:54] [INFO] - Connected (version 2.0, client OpenSSH_9.2)
[13-02-24 13:30:55] [INFO] - Authentication (password) successful!
[13-02-24 13:30:55] [INFO] - Start the target app ...
failed to get the task for process 1507

I installed latest Frida and am jailbroken with palera1n on iOS 16.7, iPhone X. 

Any idea what the issue might be? 

Frida itself seems to work, like all test commands went through smoothly.

After executing the command once, the app is stuck and I have to restart the device to use it again.

**Comment by noobpk** [comment]
You can try using -n option (attach mode) and launch the app at the same time as running the command.

**Comment by xL0b0** [comment]
> You can try using -n option (attach mode) and launch the app at the same time as running the command.

When I run` /ioshook -n 'App Store' --dump-memory --string`

I just get: `unable to attach to the specified process`

 I also opened app manually

**Comment by xL0b0** [comment]
I read about this post:

https://github.com/frida/frida/issues/1334

But the problem is that there's only that one Frida version and not a "Pre A12" for me on the Frida Repo

**Comment by noobpk** [comment]
Are you try -n option with another script like bypass jailbreak, . .
