### ISSUE TITLE
Missing credit 

### ISSUE THREAD

**Issue by interference-security** [noobpk/frida-ios-hook#12]
@noobpk I noticed you removed credit to original author: https://github.com/interference-security/frida-scripts/tree/master/iOS

**Comment by noobpk** [comment]
Sorry! My mistake. I was added references to your repo. 
You can check at : https://github.com/noobpk/frida-ios-hook/commit/9cd285c3f0c7226cd7c1ec0bcd5c936fc0bc20bb

**Comment by interference-security** [comment]
Thank you
