### ISSUE TITLE
TypeError: cannot read property [class name] of undefined, find-all-methods-all-classes.js

### ISSUE THREAD

**Issue by tloki** [noobpk/frida-ios-hook#3]
when running `/find-all-methods-all-classes.js` - many methods are listed, until class name has a "." (dot) in its name, for example:

<img width="488" alt="image" src="https://user-images.githubusercontent.com/26622655/105134137-37370100-5aee-11eb-8e88-92f5fb9a01e0.png">

**Expected behavior**
Should at least skip classes like that or try to list its methods (if those even are classes?)

 - OS: macOS Mojave (intel, macbook pro), iOS 14.2, iPhone 7

How does one approach this issue?

**Comment by noobpk** [comment]
Ahh!! It is an issue when using ``eval()`` .
And it was an old issue : https://github.com/frida/frida-objc-bridge/issues/1

**Comment by noobpk** [comment]
Let me know if there are problems during use. 
Thanks @tloki
