### ISSUE TITLE
Get base address on iOS?

### ISSUE THREAD

**Issue by Toshiba1127** [noobpk/frida-ios-hook#4]
Sorry for being ignorant. Since Google sucks and always give me link to this repo, I have no choice but to ask here.
I want to hook binary of the game. All scripts examples here are just for Obj-c, so they are no use for me. 
How can I get base with target address to hook? I tried this which works on Android but it doesn't work on iOS

`Interceptor.attach(Module.findBaseAddress('global').add(0x101903A18)`

**Comment by noobpk** [comment]
No problem. You can refer to this issue https://github.com/frida/frida/issues/1018. I think it will solve your problem.

**Comment by Toshiba1127** [comment]
I figured it out. Address must be `0x1903A18` instead `0x101903A18` as seen in IDA
