### ISSUE TITLE
Doesn't work with the latest frida version

### ISSUE THREAD

**Issue by SolorzanoJose** [noobpk/frida-ios-hook#5]
**Describe the bug**
Running app-list or trying to spawn results in "unable to launch iOS app: The operation couldn’t be completed. Application info provider (FBSApplicationLibrary) returned nil for """

**To Reproduce**
1. Install latest frida on mac and iPhone
2. Try to use frida-ios-hook
3. unable to launch iOS app: The operation couldn’t be completed. Application info provider (FBSApplicationLibrary) returned nil for ""

**Expected behavior**
Process spawns or. I get a list of apps

**Comment by noobpk** [comment]
Hi, Can you give me environmental information with the version frida is using on ios and macOS. 
Are you jailbreak your device ?

**Comment by noobpk** [comment]
Currently I was test with Frida version 14.2.13 on both macOS and iOS device. And everything are working oke.

**Comment by SolorzanoJose** [comment]
Yes, jailbroken iPhone 12 pro max with iOs 14.2.1 using unc0ver. Frida team said listing apps is indeed currently broken so not sure how you're making it work because compatibility is broken at the moment

**Comment by noobpk** [comment]
Ohh, I was checked on iPhone 6s with iOS 13.2.3. Maybe have some issue with new iOS version. I will check with high iOS version and update soon ^^
