### ISSUE TITLE
Frida not being recognized

### ISSUE THREAD

**Issue by Mr-Tomahawk** [noobpk/frida-ios-hook#56]
Hello, I am also in the comments of the youtube video so this is a bit of a double post, I tried to setup frida on both a windows and Mac laptop and both times I was met with this strange error where frida wasn’t being recognized despite being installed:

./ioshook -h
Traceback (most recent call last):
File “/Users/user/Downloads/frida-ios-hook-3.7/frida-ios-hook/core/hook.py”, line 1, in <module> import frida
ModuleNotFoundError: No module named “frida”

how do I fix this? Thank you

**Comment by noobpk** [comment]
Hi,
Sorry for late reply.
Please install [@frida ](https://github.com/frida/frida) here or install via requirements.txt : `pip3 install -r requirements.txt`
