### ISSUE TITLE
Dump memory does not dump game binaries

### ISSUE THREAD

**Issue by VanHoevenTR** [noobpk/frida-ios-hook#60]
It seems the Dump memory feature does not dump game binaries, especially Unity baed games with UnityFramefork binary. I searched for some pattern through all dump files using 010 editor but found nothing. I am missing something?

I know I can dump IPA but I would like to dump in real time to see changes

**Comment by noobpk** [comment]
Hi,
You can read more about dump memory option at here : https://github.com/Nightbringer21/fridump
