### ISSUE TITLE
Please support frida 16.0.1

### ISSUE THREAD

**Issue by kyoshiro972** [noobpk/frida-ios-hook#61]
**Describe the bug**
not compatible with frida 16.0.1

**To Reproduce**
1. update frida (pip install -U frida frida-tools)
2. update frida on Cydia. 
3. run command
4. error

**Screenshots**
[Screen Shot 2022-10-09 at 09 53 07](https://user-images.githubusercontent.com/4944743/194733930-33931d9f-0d17-48bd-bab4-457e4dc544c1.png)

**Desktop (please complete the following information):**
 - OS: 10.14.6
 - Frida version: 16.0.1

**Smartphone (please complete the following information):**
 - Device: iPhone8,4
 - OS: iOS13.3.1
 - Frida version: 16.0.1
 - Jailbreak type: checkra1n
 - Checkra1n ver: 0.12.4

**Comment by sasa8810** [comment]
Try reinstall Frida in Cydia and don’t use checkra1n use Odysseyra1n

**Comment by noobpk** [comment]
Frida-ios-hook will support latest frida version in next release. Thanks for using <3
