### ISSUE TITLE
ModuleNotFoundError: No module named 'frida'

### ISSUE THREAD

**Issue by CorbinGit** [noobpk/frida-ios-hook#64]
1. Ran command "python3 ioshook.py"
2. Produces 
Traceback (most recent call last):
  File "C:\frida\frida-ios-hook\core\hook.py", line 1, in <module>
    import frida
ModuleNotFoundError: No module named 'frida'

 - OS: Windows 10

**Comment by noobpk** [comment]
Please read Readme.md first. Thanks
