### ISSUE TITLE
DumpDecrypt issue

### ISSUE THREAD

**Issue by Kediel** [noobpk/frida-ios-hook#71]
**Describe the bug**
I run iProxy 2222 22 and I connect to my client via USB then immediately get an error saying Auth (password) failed. Is this a password on the app itself or a password i'm failing to pass along via iproxy??

**To Reproduce**
1. Connect device via USB.
2. On a terminal tab run _iproxy 2222 22_
3. On a seperate tab go to frida-ios-hook-3.7/frida-ios-hook/ folder after following install directions of latest release.
4. run _./ioshook -p [app identifier] --dump_
5. See below for error message.

**Expected behavior**

**Screenshots**
<img width="635" alt="Screenshot 2022-12-02 at 11 41 11" src="https://user-images.githubusercontent.com/13355860/205341951-050472df-19fd-4beb-b66f-6d2b384b4637.png">

**Desktop (please complete the following information):**
 - OS: Ventura 13.0.1
 - Hardware: M2

**Smartphone (please complete the following information):**
 - Device: jailbroken iPhone 6
 - OS: iOS12.5.6

**Additional context**
Tried frida-ios-dump too and it did not work as well.

**Comment by Kediel** [comment]
Also tried -m bypass-jb option as well:

<img width="647" alt="Screenshot 2022-12-02 at 11 58 09" src="https://user-images.githubusercontent.com/13355860/205345068-f116e164-cf66-4a06-a852-107f215d167b.png">

**Comment by Kediel** [comment]
**Update**: Resolved authentication issue by changing the default password in /core/utils/dump.py.

Still seeing the following issues:
<img width="646" alt="Screenshot 2022-12-03 at 11 32 00" src="https://user-images.githubusercontent.com/13355860/205451309-7709cc13-88b5-41ef-b06b-8bab763a07ac.png">

**Comment by noobpk** [comment]
What version of Frida do you use?
With the new Frida version 16.0.x it doesn't work. I am trying to fix it.

**Comment by Kediel** [comment]
I have frida 15.1.17 installed.

Note: My issue may also stem from my use of an ARM based architecture. I was able to dump most of an app with Clutch but that also gave me issues.

**Comment by noobpk** [comment]
It comes from Frida-Core. You can find a better repo while waiting for the fix. ^^!
